# From galaxy
- src: elboletaire.transmission
  name: transmission
- src: jdauphant.nginx
  name: nginx
- src: geerlingguy.nfs
  name: nfs
- src: git+https://github.com/bg-o/ansible-sonarr.git
  name: sonarr
- src: thefinn93.letsencrypt
  name: letsencrypt
- src: cmacrae.couchpotato
  name: couchpotato
- src: rahul0705.rtorrent
  name: rtorrent
